### ISSUE TITLE
Improve network protocol integration

### ISSUE THREAD

**Issue by peteral** [peteral/softplc#37]
- provide one factory class annotated as NetworkProtocol 
- this class returns a list of task and response factories 
- the NetworkProtocol annotation also provides a list of ports the protocol is bound to 
- the soft plc will listen on many ports, the dispatching will work the same way as now, however only TaskFactories registered to the incmoning port will be asked if they feel responsible

**Comment by peteral** [comment]
scan for all jars in a specific folder and add them to class path so the config file modification is no longer neccessary after an update

**Comment by networkprotocol** [comment]
Stop spamming me please.

Thanks,
Senad Brkic
